
function legacyFresh(){const p=global.ProcessCore.fresh();p.version=1;p.tags=p.tags.map(t=>{const x={...t,kind:'range',row:'2',column:'2',endRow:'4',endColumn:'2'};for(const k of ['start','sheetMode','sheetIndex','endRowMode','endRowBy','endColumnMode','endColumnBy'])delete x[k];return x;});return p;}
const {test}=require('node:test'),assert=require('node:assert/strict');
require('../src/process-core.js');require('../src/labeling-core.js');const C=global.LabelingCore,P=global.ProcessCore;
function config(){const p=legacyFresh();p.tags=[{...p.tags[0],name:'Sales',kind:'cell',row:'2',column:'2',format:'number'},{...p.tags[0],id:'q',name:'Quantity',kind:'cell',row:'2',column:'3',format:'number'}];p.steps=[{input:'Sales',op:'divide',rightKind:'tag',right:'Quantity',result:'Price'}];p.output.columns=[{label:'Sales',tag:'Sales'},{label:'Price',tag:'Price'}];return p;}
function entry(name='main.xlsx',sales=100,q=5){return {id:name,name,book:{name,sheets:[{name:'Sheet1',rows:[['name','Sales','Quantity'],['a',sales,q]]}]},included:true,typeId:'',overrides:Object.create(null),editErrors:{},acknowledged:false};}
test('raw value corrections recalculate dependent tags without changing workbook or Process',()=>{const p=config(),e=entry();e.overrides.Sales=[[200]];const result=C.analyze(e,p);assert.equal(result.status,'normal');assert.deepEqual(result.tags.get('Price'),[[40]]);assert.equal(e.book.sheets[0].rows[1][1],100);assert.equal(p.tags[0].name,'Sales');});
test('manual type resolves unmatched file and missing data can be corrected',()=>{const p=config();p.types[0].conditions[0].value='_main';const e=entry('unknown.xlsx');assert.equal(C.analyze(e,p).status,'unmatched');e.typeId='type-1';assert.equal(C.analyze(e,p).status,'normal');e.book.sheets[0].rows[1][1]='bad';assert.equal(C.analyze(e,p).status,'error');e.overrides.Sales=[[300]];assert.equal(C.analyze(e,p).status,'normal');});
test('classification conflict requires an explicit type, not just acknowledgment',()=>{const p=config();p.types.push({...p.types[0],id:'conflict',name:'other'});const e=entry();e.acknowledged=true;e.result=C.analyze(e,p);assert.equal(e.result.status,'review');assert.equal(C.gate([e]).ready.length,0);});
test('blank data, numeric bounds and always-review rules produce warnings',()=>{const p=legacyFresh();p.tags[0]={...p.tags[0],kind:'cell',row:'2',column:'2',min:'200'};const e=entry();assert.equal(C.analyze(e,p).status,'review');p.tags[0].min='';e.book.sheets[0].rows[1][1]=null;assert.equal(C.analyze(e,p).status,'review');e.book.sheets[0].rows[1][1]=500;p.tags[0].review='always';assert.equal(C.analyze(e,p).status,'review');});
test('read errors are isolated; invalid edit drafts prevent processing',()=>{const p=config(),good=entry(),bad=entry('bad.xlsx');bad.readError='손상';good.editErrors.Sales='잘못된 숫자';good.result=C.analyze(good,p);bad.result=C.analyze(bad,p);assert.equal(good.result.status,'error');assert.equal(good.result.rows,null);assert.equal(bad.result.status,'error');good.editErrors={};good.result=C.analyze(good,p);assert.equal(C.gate([good,bad]).ready.length,1);});
test('confirmed snapshot freezes edits, concatenates table rows and records skipped files',()=>{const p=config(),a=entry('a.xlsx'),b=entry('b.xlsx'),c=entry('c.xlsx');b.readError='损坏';c.included=false;for(const e of [a,b,c])e.result=C.analyze(e,p);const snap=C.snapshot([a,b,c],p);assert.equal(snap.files.length,1);assert.equal(snap.skipped.length,2);assert.deepEqual(snap.rows,[['Sales','Price'],[100,20]]);a.overrides.Sales=[[900]];a.result.tags.get('Sales')[0][0]=800;p.name='changed';assert.equal(snap.files[0].tags.Sales[0][0],100);assert.notEqual(snap.process.name,'changed');});
test('warnings require review or explicit inclusion; excluded files are never processed',()=>{const p=config(),e=entry();p.tags[0].min='200';e.result=C.analyze(e,p);assert.throws(()=>C.snapshot([e],p),/없습니다/);assert.equal(C.snapshot([e],p,{allowWarnings:true}).files.length,1);e.acknowledged=true;assert.equal(C.snapshot([e],p).files.length,1);e.included=false;assert.throws(()=>C.snapshot([e],p,{allowWarnings:true}),/없습니다/);});
test('matrix correction accepts TSV and JSON but rejects uneven rows and nonnumeric values',()=>{assert.deepEqual(C.parseGrid('1\t2\n3\t4','number'),[[1,2],[3,4]]);assert.deepEqual(C.parseGrid('[[1],[2]]','number'),[[1],[2]]);assert.throws(()=>C.parseGrid('1\t2\n3'),/같아야/);assert.throws(()=>C.parseValue('oops','number'),/숫자/);});
test('Excel cell error remains an error for text tags too',()=>{const p=legacyFresh();p.tags[0]={...p.tags[0],kind:'cell',row:'2',column:'2',format:'text'};const e=entry();e.book.sheets[0].rows[1][1]={error:'#DIV/0!'};assert.equal(C.analyze(e,p).status,'error');});
test('strict Process policy blocks issues; normal-only policy excludes even acknowledged warnings',()=>{const p=config(),a=entry('a.xlsx'),b=entry('b.xlsx');p.tags[0].min='150';b.overrides.Sales=[[200]];for(const e of [a,b])e.result=C.analyze(e,p);p.processingPolicy='block';assert.throws(()=>C.snapshot([a,b],p,{allowWarnings:true}),/해결/);a.acknowledged=true;assert.equal(C.snapshot([a,b],p).files.length,2);p.processingPolicy='normalOnly';assert.equal(C.snapshot([a,b],p).files.length,1);});
test('numeric overflow and reversed review bounds cannot silently produce a valid result',()=>{assert.throws(()=>P.compute([[1e308]],'multiply',[[1e308]]),/범위/);assert.throws(()=>C.parseValue('1e999'),/범위/);const p=config();p.tags[0].min='200';p.tags[0].max='100';assert.equal(C.analyze(entry(),p).status,'error');});
