const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');require('../src/process-core.js');require('../src/labeling-core.js');const C=ProcessCore,L=LabelingCore;
function legacy(){return {version:1,id:'old',name:'기존 설정',types:[{id:'t',name:'일반',mode:'all',conditions:[{kind:'filename',operator:'contains',value:'.xlsx'}]}],tags:[{id:'x',type:'t',name:'값',sheet:'Sheet1',kind:'column',row:'2',column:'2',endRow:'',endColumn:'',format:'auto',min:'5',review:'always'}],steps:[],output:{kind:'table',columns:[{id:'o',label:'값',tag:'값'}]},processingPolicy:'block'};}
const book={name:'1_main_a.xlsx',sheets:[{name:'Sheet1',rows:[['a','b'],['a',10],['b',20],['c',null],['d',null]]},{name:'다른 시트',rows:[['a','b','c'],['a',2,3],['b',4,5],['c',null,7]]}]};
test('v1 migration keeps original bounds, review settings, policy, ID and source immutability',()=>{const p=legacy(),before=JSON.stringify(p),n=C.normalize(p);assert.equal(n.version,2);assert.equal(n.id,'old');assert.equal(n.tags[0].start,'B2');assert.equal(n.tags[0].endRowMode,'sheet-end');assert.equal(n.tags[0].min,'5');assert.equal(n.processingPolicy,'block');assert.deepEqual(C.evaluate(book,n).rows,[['값'],[10],[20],[null],[null]]);assert.equal(JSON.stringify(p),before);});
test('v1 fixed ranges and horizontal sheet extent retain all cells',()=>{const p=legacy();p.tags[0]={...p.tags[0],kind:'range',endRow:'3',endColumn:'2'};assert.deepEqual(C.evaluate(book,p).rows,[['값'],[10],[20]]);const n=C.normalize({...p,tags:[{...p.tags[0],kind:'row',endColumn:''}]});assert.equal(n.tags[0].endColumnMode,'sheet-end');assert.deepEqual(C.evaluate(book,n).rows,[['값'],[10]]);});
test('new indexed sheet + dynamic table + chosen column cooperate with manual classification and corrections',()=>{const p=C.fresh();p.types[0].conditions=[{kind:'filename-token',delimiter:'_',part:'2',operator:'equals',value:'main'}];p.tags[0]={...p.tags[0],name:'표',sheetMode:'index',sheetIndex:'2',kind:'range',start:'B2',endRowMode:'until-blank',endRowBy:'B',endColumnMode:'last-data',endColumnBy:'2'};p.output.columns[0]={...p.output.columns[0],tag:'표',tableColumn:'2'};assert.deepEqual(C.evaluate(book,p).rows,[['값'],[3],[5]]);const unmatched={...book,name:'unknown.xlsx'};assert.equal(C.evaluate(unmatched,p).classification.type,null);assert.deepEqual(C.evaluate(unmatched,p,{typeId:'type-1',values:{표:[[8,9],[10,11]]}}).rows,[['값'],[9],[11]]);assert.equal(book.sheets[1].rows[1][2],3);});
test('error cells and overflowing arithmetic remain errors after merge',()=>{const p=C.fresh();p.tags[0]={...p.tags[0],kind:'cell',start:'B2',format:'text'};const b={...book,sheets:[{name:'Sheet1',rows:[['a','b'],['a',{error:'#VALUE!'}]]}]};assert.match(C.evaluate(b,p).errors.join(''),/Excel 셀 오류/);for(const op of ['multiply','add','divide'])assert.throws(()=>C.compute([[1e308]],op,[[op==='divide'?1e-308:1e308]]),/범위/);assert.throws(()=>C.compute([[1e308,1e308]],'sum'),/범위/);});
test('invalid legacy coordinates and empty user types are not silently repaired',()=>{const p=legacy();p.tags[0].row='0';assert(C.evaluate(book,p).errors.length);assert(C.validate({...p,types:[],tags:[]}).some(e=>e.includes('하나 이상')));});
test('shared storage reads v1/v2, preserves default ID, notifies saves and does not mutate storage on read',()=>{
 const map=new Map([['WindowStarter.Processes.v1',JSON.stringify([legacy()])],['WindowStarter.DefaultProcess.v1','old']]),events={};
 const ctx={window:{},ProcessCore:C,localStorage:{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)},addEventListener:(name,fn)=>events[name]=fn,crypto:{randomUUID:()=> 'new'}};
 vm.runInNewContext(fs.readFileSync(require.resolve('../src/process-store.js'),'utf8'),ctx);const S=ctx.window.ProcessStore,before=map.get('WindowStarter.Processes.v1');assert.equal(S.list()[0].version,2);assert.equal(map.get('WindowStarter.Processes.v1'),before);assert.equal(S.defaultId(),'old');let called=0;const unsubscribe=S.subscribe(()=>called++);const fresh=S.save(C.fresh());assert.equal(fresh.id,'new');assert.equal(S.list().length,2);assert.equal(called,1);unsubscribe();S.setDefault('new');assert.equal(called,1);assert.equal(S.defaultId(),'new');
});
